# Generated by Django 3.0.3 on 2020-05-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_number', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major_requirement',
            fields=[
                ('major_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.Major')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transferevaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_year_taken', models.CharField(blank=True, max_length=8, null=True)),
                ('expiration_date', models.DateField()),
                ('approved_status', models.CharField(blank=True, max_length=1, null=True)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('approver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.Approver')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.Course')),
                ('major_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.Major_requirement')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.School'),
        ),
    ]
